#!/bin/sh

source ~/.config/zsh/exports.zsh

clock=$(date '+%I')

case "$clock" in
	"00") icon="🕛" ;;
	"01") icon="🕐" ;;
	"02") icon="🕑" ;;
	"03") icon="🕒" ;;
	"04") icon="🕓" ;;
	"05") icon="🕔" ;;
	"06") icon="🕕" ;;
	"07") icon="🕖" ;;
	"08") icon="🕗" ;;
	"09") icon="🕘" ;;
	"10") icon="🕙" ;;
	"11") icon="🕚" ;;
	"12") icon="🕛" ;;
esac

case $BLOCK_BUTTON in
  1) notify-send "This Month" "$(cal)" && notify-send "Appointments" "$(calcurse -a)" && notify-send "Todo's" "$(calcurse -t | grep -E '[0-9].')" ;;
	2) setsid -f "$TERMINAL" -e calcurse ;;
	3) notify-send "📅 Time/date module" "\- Left click to show upcoming appointments via \`calcurse -a\`, todo's via \`calcurse -t\` and show the month via \`cal\`
- Middle click opens calcurse if installed" ;;
	6) "$TERMINAL" -e "$EDITOR $0" ;;
esac

date "+%b %d %Y (%a) $icon %I:%M%p"

