#!/bin/sh

CURRENT_COURSE=~/Documents/notes/current-course
og_course=$(readlink ${CURRENT_COURSE})
name=$(basename ${og_course})
grade=$(yq read ${CURRENT_COURSE}/info.yaml grade)

case $BLOCK_BUTTON in
	1) $HOME/Singularis/local/scripts/school/rofi-current-course.py ;;
	2) notify-send "Grade for ${name}" "${grade}%" ;;
	3) $HOME/Singularis/local/scripts/school/rofi-lessons.py ;;
	6) "$TERMINAL" -e "$EDITOR $0" ;;
esac

echo "Current Course: [${name}]"
